Artsdatabanken/nin-kart

- package.json
- src/Naturområdedetaljer/Bestiller.jsx
- src/Naturområdedetaljer/Bestiller.stories.js
- src/Naturområdedetaljer/Detaljer.jsx
- src/Naturområdedetaljer/Kartlegging.jsx
- src/Naturområdedetaljer/Kontakt.jsx
- src/Naturområdedetaljer/Kontakt.stories.js
- src/Naturområdedetaljer/Naturnivå.jsx
- src/Naturområdedetaljer/Naturområdedetaljer.jsx
- src/Naturområdedetaljer/Naturområdedetaljer.stories.js
- src/Storyshots.test.js
- src/__snapshots__/Storyshots.test.js.snap
- yarn.lock
Eksempel på konvertering fra nin til ny
> Upgrade sample

- src/Kart/Mapbox/Mapbox.jsx
> Testing Che's NIN tiles

- README.md
- package.json
- yarn.lock
https://github.com/prettier/prettier
> Add prettier opinionated javascript formatter 

- .travis.yml
> Reenable tests on build server

- src/App.js
> Jarle ønsker komplementære farger

- src/App.js
- src/FinnKode/FinnKode.js
- src/Kodetre/Kodeliste/KodelisteContainer.js
- src/TopBar/TopBar.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> Hektet på fritekstsøk, må poleres

- src/TopBar/TopBar.js
- src/__snapshots__/Storyshots.test.js.snap
> Bruk riktig meny symbol (ikke reorder med 4 linjer på)

- src/Kodetre/Kodeliste/KodelisteContainer.js
- src/Kodetre/Kodeliste/ResultatListe.js
> Klikk på element i søkersultat for å navigere til elementet

- README.md
- package.json
- yarn.lock
> Coveralls badge

- src/FinnKode/FinnKode.js
- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/control-panel.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/KodelisteContainer.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/Naturområdedetaljer/Omrader.jsx
- src/backend.js
Mulig å søke med 2 tegn
Testkode for å legge til kalklag
Legg til lag viser navn istedenfor kode
Kommune <> Fylke
Skjuler bytt farge der det ikke er enkeltfarge
Tester hente data fra data.beta.artsdatabanken.no/api/Graph/NiN2.0/
> Diverse bugfix

- src/Kart/Kart.jsx
- src/Naturområdedetaljer/PointInfo.stories.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
Fixes https://github.com/Artsdatabanken/ratatouille/commit/f69c1f8eb9085f07a5f212e8531ffdb9582d8c33#diff-6bfe66e65df6b8eb5e0a588d38a2aadfL104
> readded rasterPointMethod

- src/Kodetre/Kodeliste/Kodelisteelement.js
> Oppdatering på avatarer (rotnivå og geografi)

- src/Kart/Mapbox/Mapbox.css
> Mapbox logo

- src/Kodetre/Kodeliste/Kodekort.js
- src/__snapshots__/Storyshots.test.js.snap
- src/rename.js
> Kodekort - fast størrelse

- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/VenstreVinduContainer.stories.js
- src/__snapshots__/Storyshots.test.js.snap
- yarn.lock
> Coverbilder på nin-typer

- src/App.js
- src/Grunnkart/Grunnkart.js
- src/Grunnkart/MainDrawer.js
- src/Grunnkart/NavigationChevronLeftDouble.js
- src/Kart/Kart.jsx
- src/Naturområdedetaljer/Punktinformasjon.jsx
- src/__snapshots__/Storyshots.test.js.snap
> Logo i hovedmeny

- src/Grunnkart/Grunnkart.stories.js
- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/Naturområdedetaljer/PunktinformasjonContainer.test.js
- src/__snapshots__/Storyshots.test.js.snap
> added adb logo for rødlisteKategori

- src/Naturområdedetaljer/PunktinformasjonContainer.js
> don't show link for description

- src/Kart/Mapbox/Mapbox.jsx
- src/__snapshots__/Storyshots.test.js.snap
> Mouse cursor på kartet

- README.md
- Fjern duplikat Coveralls
- Fjern broken "dependencies"
> Rydd opp i badges

- src/Components/StepSliderContainer.stories.js
- src/FilterTree/FilterTree.stories.js
- src/Naturområdedetaljer/PointInfo.js
- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/__snapshots__/Storyshots.test.js.snap
show metadata-link if article missing
removed unneeded mount
> actual link for NA-codes

- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/Mapbox.jsx
- src/Naturområdedetaljer/PointInfo.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> Fjernet layer manager knapp.. la til vis katalog-knapp

- src/FinnKode/FinnKode.js
- src/rename.js
> API Casing temp hack 

- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/Mapbox.jsx
- src/Kart/Mapbox/style-lookup.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Statistikk/Illustrasjon.js
- src/__snapshots__/Storyshots.test.js.snap
> Lys opp kartet ved hover i lista

- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/rename.js
> Tweak på kodetretittel

- package.json
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/KodeVindu.stories.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- yarn.lock
> Color picker

- src/Kodetre/Kodeliste/Checkboard.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/KodeVindu.stories.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/PaintSwatch.js
- src/__snapshots__/Storyshots.test.js.snap
> Fix transparency on swatch

- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/KodeVindu.stories.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodetagg.js
- src/__snapshots__/Storyshots.test.js.snap
- Norske navn
- Themeable kodetagg
> Rydding i metabasen.

- src/Kart/Mapbox/Mapbox.jsx
> Rename color -> farge

- src/Kart/Mapbox/Mapbox.jsx
- src/Kart/Mapbox/style-lookup.js
- src/Kart/naturtypekart_style.json
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> Ny metabase

- src/Kodetre/Kodeliste/Kodelisteelement.js
> Code picker repair

- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/VenstreAvatar.js
- src/Kodetre/Kodetagg.js
- src/__snapshots__/Storyshots.test.js.snap
Transparent fylke
Midlertidig random farger på koder som ikke har styling
> Styling fixes

- src/Kodetre/Kodeliste/ResultatListe.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
søkeresultater vises, gjenstår hva som skal gjøres med kodene da det ikke lenger er samsvar mellom firebase og kodesøket
> Oppdatert url til søk

- src/Kodetre/Kodeliste/KodeVindu.js
> Stygg 'vis i kart' knapp

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/Kodetre/Kodeliste/ResultatListe.stories.js
- src/Kodetre/Kodeliste/RotAvatar.js
- src/SearchBox/SearchBox.js
- src/SearchBox/SearchBox.stories.js
- src/TopBar/TopBar.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
- Viser feilmeldinger fra API på skjerm
- Fjerner horisontal scrolling i resultatliste
- Highlighter treff i resultatlista
- Justert layout på resultatliste
- Justert layout på søkeboks
- Viser valgt tema i søkeboksen (i grått)
> Søkeforbedring

- src/Kart/Mapbox/style-lookup.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
> Bildeskalering

- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/Mapbox.jsx
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
* workaround for koder med _[a-z]
* vis mengdearter
* byttet default bildetype til jpg
* bugfix vis utbredelse
> * gå til bbox for naturtype

- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> Vis avatarer

- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/VenstreAvatar.js
- src/__snapshots__/Storyshots.test.js.snap
* beskrivelse for relasjonslister
> * default-bilder ved error

- src/Kart/Mapbox/dark.json
- src/Kart/Mapbox/default.json
- src/Kart/Mapbox/satellite.json
- src/Kart/Mapbox/style-lookup.js
- src/Kart/Mapbox/vintage.json
* fjernet tx_overlay fra style-files
> * viser fylker og kommuner igjen

- src/Kart/Mapbox/style-lookup.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/__snapshots__/Storyshots.test.js.snap
* skjul områder/areal om ikke dette kommer fra api
* kodeendringer for å linke til rødlistekategori
* vis kalk i kart
> * viser mer metadata

- src/Kodetre/Kodeliste/KodeContainer.stories.js
- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> add namespace to key for raster-pointInfo

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/KodeVindu.stories.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> Gjør URLer lesbare for mennesker

- package.json
- src/Kodetre/Kodeliste/KodeVindu.stories.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/backend.js
- yarn.lock
> Upgrade dependencies

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/Kodetre/Kodeliste/ResultatListe.test.js
- src/Kodetre/Kodeliste/__snapshots__/ResultatListe.test.js.snap
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> Redirect fra koder (253MB meta)

- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
> Positioning tweaks

- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/index.js
- src/Kodetre/Kodeliste/KodeVindu.stories.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
> * lagrer egne farger i localstorage

- src/Kart/Mapbox/index.js
> * bugfix localstorage

- src/Kodetre/Kodeliste/Kodekort.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
Images in 1x, 1.5x and 2x resolution
> Source set test

- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/index.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/__snapshots__/Storyshots.test.js.snap
> * badge viser antall arter og naturområder

- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/Kodetre/Kodeliste/ResultatListe.stories.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
- src/rename.js
- src/rename.test.js
> * styling for søkeresultat

- src/Kart/Mapbox/__snapshots__/style-lookup.test.js.snap
- src/Kart/Mapbox/index.js
- src/Kart/Mapbox/style-lookup.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
oppdatert aktiv/opplyst-stil for å gjøre det tydligere hva som er valgt/hover
Viser foreldrenavn i søkeresultat
#180 
#185 
#194 : Tydeligere kontrast på omriss
> oppdatert aktiv/opplyst-stil 

- src/Naturområdedetaljer/PunktinformasjonContainer.js
> * Viser mer naturområdeinfo

- src/Grunnkart/Grunnkart.js
> * bugfix back-knapp

- src/App.css
> Smalere scroll bar

- .flowconfig
- package.json
- src/Kodetre/Kodeliste/KodeContainer.js
- src/backend.js
- yarn.lock
Legger inn flow
- [Flow.org](https://flow.org/en)
> Fixes #209

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> Fixes #212

- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
Vis kommunevåpen uten crop sirkel
> Fixes #214

- src/Kodetre/Kodeliste/ResultatListe.js
- src/Kodetre/Kodeliste/__snapshots__/ResultatListe.test.js.snap
> Fixes #216

- src/Kodetre/Kodeliste/ResultatListe.js
- src/__snapshots__/Storyshots.test.js.snap
> Fixes #206

- src/Kodetre/Kodeliste/KodeContainer.js
> * fix #211

- src/Kart/Mapbox/index.js
- src/backend.js
https://bboxcode.firebaseio.com/observations/TX_93.json
https://test.artsdatabanken.no/data/json/observationsGroup/TX_93.json
> New format for aggregated observations

- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodetagg.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> Viser koder under tvil

- src/App.test.js
- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/backend.js
- src/backend.test.js
> * viser miljøvariabler

- src/Kart/Mapbox/__snapshots__/style-lookup.test.js.snap
- src/Kart/Mapbox/dark.json
- src/Kart/Mapbox/default.json
- src/Kart/Mapbox/satellite.json
- src/Kart/Mapbox/style-lookup.js
- src/Kart/Mapbox/vintage.json
> * lagt til den nye kalklaget

- src/Kart/Mapbox/index.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Naturområdedetaljer/PointInfo.js
- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
* bugfix bounds og tooltip på sizebar
* ikoner for flere firma -> default hentes fra firebase
> * La til NavigationControls, +/- og rett opp

- src/Kart/Mapbox/index.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
* bugfix opplyst lag kom aldri frem
> * fix #234 - bruk meta.sti om den finnes, ellers kode

- src/Kodetre/Kodeliste/Kodeliste.js
- src/__snapshots__/Storyshots.test.js.snap
> Sorter kodeliste

- src/Kart/Mapbox/index.js
> Smaller cell size deck gl

- .eslintrc.json
- package.json
- yarn.lock
Erstatt håndkode med pretty-quick modulen
> Tuning av prettier-integrasjon

- src/VenstreVinduContainer.js
> fikser #187 ved å ikke gjøre treet og søkeresultat gjensidig utelukkende

- src/Kart/Mapbox/MapStyle.js
- src/Kart/Mapbox/__snapshots__/style-lookup.test.js.snap
- src/Kart/Mapbox/default.json
- src/Kart/Mapbox/naturtypekart_style.json
- src/Kart/Mapbox/style-lookup.js
all tags are lowercase
uses prefixes for bs and rl
> moved to new version of naturomrader

- src/Kart/Mapbox/style-lookup.js
> fikser #246, behandles likt som NA

- src/Kart/Mapbox/index.js
- src/Kodetre/Kodeliste/ColorPicker.stories.js
- src/__snapshots__/Storyshots.test.js.snap
> move taxonLayer out of render

- src/Naturområdedetaljer/PunktinformasjonContainer.js
> Punktinformasjon tagget BS som MI, fikset

- src/Grunnkart/Grunnkart.js
- src/Kart/index.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/__snapshots__/Storyshots.test.js.snap
Inspill til #191 - setter annen farge dersom areal = 0, bør byttes ut med noe annet om api kan levere om det finnes data i gjeldende eller undernoder
> Fix #224 - nullstiller localId

- package.json
- src/index.js
- yarn.lock
> Fix #239 - må legge til babel polyfill for at det skal fungere i IE

- src/App.test.js
- src/Kart/Mapbox/index.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> Arter observert

- src/Grunnkart/Grunnkart.js
- src/Grunnkart/MainDrawer.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/ValgtListe.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> Mulig å legge til koder i en liste med valgte koder

- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/index.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/ValgtListe.js
> Legger til/fjerner lag fra lista

- src/Kart/Mapbox/index.js
> fikk en kræsj ifm med at lag ble lagt til flere ganger

- src/Kart/Mapbox/index.js
- src/__snapshots__/Storyshots.test.js.snap
> Viser antall arter i popup på kartet

- src/Kart/Mapbox/MapStyle.js
- src/Kart/Mapbox/__snapshots__/style-lookup.test.js.snap
- src/Kart/Mapbox/default.json
- src/Kart/Mapbox/naturtypekart_style.json
- src/Kart/Mapbox/style-lookup.js
- src/Kart/Mapbox/style-lookup.test.js
> moved mbtile to adb server running tileserver. use only one mbtile

- src/Kart/Mapbox/__snapshots__/style-lookup.test.js.snap
- src/Kart/Mapbox/default.json
- src/Kart/Mapbox/style-lookup.js
- src/Kart/Mapbox/style-lookup.test.js
- src/Naturområdedetaljer/PunktinformasjonContainer.test.js
> remove special handling of top nodes

- src/Kart/Mapbox/default.json
- src/Kart/Mapbox/style-lookup.js
> use tile-url directly. remove mapbox adb-layers

- src/Kart/Mapbox/index.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/ValgtListe.js
- src/Kodetre/Kodetagg.js
- src/__snapshots__/Storyshots.test.js.snap
> Tooltip på del/velg/favoritt-ikoner, Viser hele koden for valgte elementer

- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/index.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
Bugfixer som følge av koder ikke følger standard med å enten være store eller små bokstaver
> Debounce opplyst-markering så den ikke henger igjen

- src/Grunnkart/Grunnkart.js
- src/Grunnkart/MainDrawer.js
- src/Kart/Mapbox/MapStyle.js
- src/Kart/Mapbox/light.json
- src/Kart/Mapbox/satellite.json
- src/Kart/Mapbox/vintage.json
> bakgrunnskartene virker igjen, la til lyst kart også

- src/Kart/Mapbox/index.js
> skulle ikke være debounce på fargeleggLag

- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
> fix #290 - avhenger av at link-url blir lagt til på barn i firebase

- src/Kodetre/Kodeliste/Kodekort.js
> fix #289 - bruker både norsk og scientific name

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/Graf.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/PaintSwatch.js
- src/Kodetre/Kodetagg.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
- src/språk.js
> Engelske tekster vises ikke #297

- .travis.yml
> Use node v10

- src/Kodetre/Kodeliste/ResultatListe.js
- src/__snapshots__/Storyshots.test.js.snap
- src/språk.js
> Søkeresultatet viser blanke linjer

- src/Kodetre/Kodeliste/ResultatListe.js
- src/__snapshots__/Storyshots.test.js.snap
> Trunker strenger med ellipsis

- src/Kodetre/Kodeliste/ResultatListe.js
- src/Kodetre/Kodetagg.js
- src/__snapshots__/Storyshots.test.js.snap
> fix #306 , regex

- src/AktiveKartlag/Kartlagelement.js
- src/AktiveKartlag/index.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodetagg.js
> Verneområder i treet

- src/Kodetre/Kodetagg.js
> regex-justering siste del av kode

- src/Kart/Mapbox/index.js
- src/Kart/Mapbox/style-lookup.test.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/localStorageHelper.js
- src/localStorageHelper.test.js
- src/prettyprint.js
- src/prettyprint.test.js
Vis koder uppercase
Mulig med transparent i lagrede koder
> Forsøk på fiks av #300

- src/Naturområdedetaljer/PunktinformasjonContainer.js
> use parent code title for better readability

- src/Kart/Mapbox/MapStyle.js
- src/Kart/Mapbox/index.js
> remove shovels

- src/Kodetre/Kodeliste/BildeDialog.js
- src/Kodetre/Kodeliste/BildeDialog.stories.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> vis bilde og lisens (dummy)

- .travis.yml
- package.json
- src/Kodetre/Kodetagg.js
- src/backend.js
- yarn.lock
https://www.npmjs.com/settings/artsdatabanken/packages
> Bruk Artsdatabanken sitt typesystem

- src/Kart/Mapbox/index.js
- src/backend.js
> Cyan outline upper code

- src/Kart/Mapbox/index.js
> Artsutbredelsen hadde forsvunnet etter endring i firebase

- src/Kart/Mapbox/index.js
> fix #340: MinZoom endret fra 4 til 3

- src/Naturområdedetaljer/VectorPointInfo.js
> collapsibles default to closed

- package.json
- src/Naturområdedetaljer/Punktinformasjon.jsx
- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/__mocks__/backend.js
- src/backend.js
- yarn.lock
> Verneområde point info

- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/index.js
- src/__snapshots__/Storyshots.test.js.snap
Oppstart med å vise søk og katalogen
> mindre kartlag som henger igjen

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/rename.js
> Midlertidig slått av liste alle verneområder

- src/Kart/Mapbox/MapStyle.js
- src/Kart/Mapbox/__snapshots__/Mapbox.test.js.snap
- src/Kart/Mapbox/__snapshots__/style-lookup.test.js.snap
- src/Kart/Mapbox/dark.json
- src/Kart/Mapbox/default.json
- src/Kart/Mapbox/light.json
- src/Kart/Mapbox/naturtypekart_style.json
- src/Kart/Mapbox/satellite.json
- src/Kart/Mapbox/style-lookup.js
- src/Kart/Mapbox/vintage.json
> change to single mbtile per prefix

- src/Naturområdedetaljer/PunktinformasjonContainer.js
_______
|.-----.|
||x . x||
||_.-._||
`--)-(--`
__[=== o]___
|:::::::::::|\
Klikk på NA_I genererer spørring på metadata som ikke eksisterer
Returner hvis ingen metadata eksisterer
> return on undefined props

- src/Kodetre/Kodeliste/KodeContainer.js
- src/Naturområdedetaljer/PunktinformasjonContainer.js
All pointqueries were resent on zoom/pan
Only send pointQueries on new point
> Fixes #354

- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/Naturområdedetaljer/PunktinformasjonContainer.test.js
> Fixes #376

- src/Naturområdedetaljer/PointInfo.js
- src/Naturområdedetaljer/VectorPointInfo.js
- src/__snapshots__/Storyshots.test.js.snap
> List item text order reversed

- src/Kodetre/Kodeliste/Graf.js
```json
"prosedyrekategori": {
"NA_HT-PK1": {
"erSubset": true,
"farge": "#f49943",
"sti": "na/ht/pk/1",
"tittel": {
"nb": "Uten variasjon i artssammensetning betinget av strukturerende artsgruppe"
}
}
}
```
> Kategori vises ikke på relasjoner

- src/AktiveKartlag/Kartlagelement.js
- src/AktiveKartlag/index.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
> Fix kommunevåpen vises ikke

- src/AktiveKartlag/Kartlagelement.js
- src/App.test.js
- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/index.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
- src/localStorageHelper.js
- src/localStorageHelper.test.js
> Sentraliser overstyring av farger (DRY)

- src/AktiveKartlag/Kartlagelement.js
- src/AktiveKartlag/PolygonlagElement.js
- src/AktiveKartlag/index.js
Forrige plassering ble fjernet fra historien
> Back-knappen virker ikke fra settings-menyen

- src/AktiveKartlag/BakgrunnskartElement.js
- src/AktiveKartlag/EtiketterElement.js
- src/AktiveKartlag/Kartlagelement.js
- src/AktiveKartlag/TerrenglagElement.js
- src/__snapshots__/Storyshots.test.js.snap
> Legg til "reorder" håndtak for å bytte rekkefølge på lag

- src/Grunnkart/Grunnkart.js
Viser nå samme tilstand som aktiv kartlag menyen
> Fix: av/på knapp i katalog viser alltid av

- src/AktiveKartlag/Kartlagelement.js
- src/AktiveKartlag/index.js
- src/Tweaks/Innstilling.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
Det kan diskuteres om alt er til det bedre..
> Layout tweaks

- src/backend.js
> point backend to filestorage

- src/Kart/Mapbox/default.json
- src/Kart/Mapbox/index.js
Gjort klar for raster-visning, men vi trenger en måte å aktivere via katalog.
> Soner og seksjoner mbtiles

- src/__snapshots__/Storyshots.test.js.snap
- src/språk.js
> justering på hva som vises fra språk-objektet

- src/Naturområdedetaljer/PunktinformasjonContainer.js
> Fixes #415

- src/Kart/Mapbox/default.json
- src/Kart/Mapbox/style-lookup.js
> added soner and seksjoner vector-tiles

- yarn.lock
* react til 16.4
* react-test-renderer til 16.3.2
> Oppgrader avhengigheter

- package.json
- src/AktiveKartlag/index.js
- src/Grunnkart/Grunnkart.js
- src/Naturområdedetaljer/VectorPointInfo.js
- src/Tweaks/Label.js
- src/Tweaks/Overskrift.js
- src/Tweaks/SliderSetting.js
- src/Tweaks/index.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
- src/index.js
- yarn.lock
> Angi font i settingsmeny

- src/AktiveKartlag/TerrenglagElement.js
- src/AktiveKartlag/index.js
- src/Tweaks/Innstilling.js
- src/Tweaks/Label.js
- src/Tweaks/Overskrift.js
- src/Tweaks/SliderSetting.js
- src/Tweaks/Terreng.js
- src/Tweaks/Veksle.js
- src/Tweaks/index.js
- src/__snapshots__/Storyshots.test.js.snap
> Justering av layout på laginntillinger

- src/Tweaks/Innstilling.js
- src/__snapshots__/Storyshots.test.js.snap
Var default browser font der..
> Font på slider innstilling

- src/AktiveKartlag/index.js
- src/__snapshots__/Storyshots.test.js.snap
> Skillelinje i aktive kartlag

- src/AktiveKartlag/BakgrunnskartElement.js
- src/AktiveKartlag/Kartlagelement.js
- src/AktiveKartlag/TerrenglagElement.js
- src/__snapshots__/Storyshots.test.js.snap
Bakgrunnskart ligger fast, nederst
> Vis "reorder" håndtak bare på lag som kan dras rundt

- src/Kart/Mapbox/index.js
Fix for #397 
Nytt bbox-format fra dataflyt.
> fix: Vis i kart feiler

- src/Grunnkart/Grunnkart.js
- src/Kart/Mapbox/index.js
- src/Tweaks/index.js
- src/VenstreVinduContainer.js
- src/VenstreVinduContainer.stories.js
> Oppdater farger etterhvert som fargen endres

- src/AktiveKartlag/Kartlagelement.js
- src/AktiveKartlag/PolygonlagElement.js
- src/AktiveKartlag/index.js
- src/App.css
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Tittelblokk.js
- src/Kodetre/Kodetagg.js
- src/__snapshots__/Storyshots.test.js.snap
Viser kode med overordnede titler
test en fiks for mobil-zoom
> Parent-lag collapsible

- src/Kart/index.js
> Use 'handle' prefix for event handler

- package.json
- public/index.html
- public/manifest.json
- src/AktiveKartlag/Kartlagelement.js
- src/AktiveKartlag/PolygonlagElement.js
- src/AktiveKartlag/index.js
- src/Kodetre/Kodetagg.js
- src/__snapshots__/Storyshots.test.js.snap
- yarn.lock
fix(padding): fix #388 : Padding i tekstfelt
fix(title): fix #449 : Tab-tittel
feat(kodevisning): #384: viser koder med målestokk
> feat(indent): #361: innrykk på children

- src/Naturområdedetaljer/PunktinformasjonContainer.js
- src/Naturområdedetaljer/PunktinformasjonContainer.test.js
- src/__mocks__/backend.js
> Fixes #399

- src/backend.js
> move ninMemApi from Azure

- .travis.yml
- src/Kart/Mapbox/style-lookup.js
- yarn.lock
> read RL from NA-layer

- src/Naturområdedetaljer/PunktinformasjonContainer.js
> get article directly from fields

- src/Kodetre/Kodeliste/ResultatListe.js
- src/__snapshots__/Storyshots.test.js.snap
> Fixes #460

- src/Kodetre/Kodeliste/KodeVindu.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> Fix katalog tiny height

- src/Kodetre/Kodeliste/KodeVindu.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
No scrolling in Venstremeny on mobile
Scrolling in Venstremeny on mobile
> added scrolling

- package.json
- src/App.js
- yarn.lock
Pinching zooms on mobile
Pinching does not zoom on mobile
> added metatag to avoid zooming

- package.json
- src/Kart/Mapbox/index.js
- yarn.lock
> Fixes #479

- yarn.lock
> Upgrade coveralls & prettier

- yarn.lock
> Upgrade react

- src/Grunnkart/Grunnkart.js
- src/Grunnkart/MainDrawer.js
- src/Grunnkart/MainDrawer.stories.js
> Link til issues fra hovedmeny 'tilbakemelding'

- README.md
> Endre link fra README til klient til https://naturinorge.firebaseapp.com

- src/SearchBox/SearchBox.js
- src/TopBar/TopBar.js
- src/__snapshots__/Storyshots.test.js.snap
> Style appbar

- src/AktiveKartlag/Aktivekartlag.stories.js
- src/AktiveKartlag/BakgrunnskartElement.js
- src/AktiveKartlag/Kartlagelement.js
- src/AktiveKartlag/PolygonlagElement.js
- src/AktiveKartlag/PolygonlagElement.stories.js
- src/AktiveKartlag/TerrenglagElement.js
- src/AktiveKartlag/index.js
- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/sources.js
- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/SearchBox/SearchBox.js
- src/TopBar/TopBar.js
- src/Tweaks/Bakgrunnskart.js
- src/Tweaks/ColorPicker.js
- src/Tweaks/Polygon.js
- src/Tweaks/Terreng.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> CSS Weekend #3

- README.md
- package.json
- src/AktiveKartlag/index.js
- src/Kodetre/Kodeliste/Fakta.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Tittelblokk.js
- src/Kodetre/Kodetagg.js
- src/__snapshots__/Storyshots.test.js.snap
- yarn.lock
> Test Jenkins integrasjon

- public/style.yaml
> Kombinatorisk søk: Vis lag a, lag b og lab a+b samtidig

- src/Kart/LeafletTangram/scene/index.js
> fix(Kartlag uten barn vises ikke i kartet) 

- src/AktiveKartlag/PolygonlagElement.js
- src/AktiveKartlag/index.js
- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/KodeVindu.stories.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Naturområdedetaljer/PunktinformasjonContainer.stories.js
- src/VenstreVinduContainer.js
- src/VenstreVinduContainer.stories.js
- src/__snapshots__/Storyshots.test.js.snap
Plassinerg av lag på kartet kommer snart..
> Funksjon bak knappen for å aktivere lag

- public/style.yaml
- src/AktiveKartlag/BakgrunnskartElement.js
- src/AktiveKartlag/Kartlagelement.js
- src/AktiveKartlag/PolygonlagElement.js
- src/AktiveKartlag/TerrenglagElement.js
- src/AktiveKartlag/index.js
- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/index.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/index.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Tweaks/ColorPicker.js
- src/Tweaks/Polygon.js
- src/Tweaks/Terreng.js
- src/Tweaks/Tweaks.stories.js
- src/Tweaks/index.js
- src/VenstreVinduContainer.js
- src/VenstreVinduContainer.stories.js
- src/__snapshots__/Storyshots.test.js.snap
Nå mulig å navigere i aktive kartlag
> Navigasjon i laginnstillinger

- public/index.html
- src/Kart/index.js
> Remove mapbox dependency

- src/Grunnkart/Grunnkart.js
> Fjern avhengighet til egenskap sti i metadata

- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/index.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/KodeVindu.stories.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Tittelblokk.js
- src/VenstreVinduContainer.js
> Oppdatering av scenen uten å laste hele kartet på nytt

- src/Grunnkart/Grunnkart.js
> fix("Fjerne" aktive lag)

- public/style.yaml
- src/AktiveKartlag/index.js
- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/mal/bakgrunnskart.json
- src/Kart/LeafletTangram/scene/sources.js
- src/Kart/LeafletTangram/scene/styles.js
- src/Tweaks/bakgrunn/Bakgrunnskart.js
> Gjør dataene lettere å se på kartet

- src/Kodetre/Kodeliste/Graf.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
> fix(Navigering i katalog)

- src/Grunnkart/Grunnkart.js
> Escape = back-knapp i browser

- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/sources.js
- src/Kodetre/Kodeliste/Graf.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/VenstreVinduContainer.js
> Legg til kartlagkilder BS og RL

- src/Kart/LeafletTangram/scene/index.js
> fix(Transport forsvinner med land)

- src/AktiveKartlag/Kartlagelement.js
- src/__snapshots__/Storyshots.test.js.snap
> Tvik padding aktive lag

- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
> fix: Tekst flyter over fargeprøven

- public/style.yaml
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/lights.js
remove unused sources
use correct style for polygons
> remove duplicate light

- src/AktiveKartlag/index.js
> fix: Markering aktive kartlag ved hover vs endre farge #565

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/Kodetre/Kodeliste/__snapshots__/ResultatListe.test.js.snap
- src/SearchBox/SearchBox.js
- src/TopBar/TopBar.js
- src/TopBar/TopBar.stories.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> fix: Søkeboks ser forferdelig ut

- src/Grunnkart/MainDrawer.stories.js
- src/Kodetre/Kodeliste/Fakta.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodetagg.stories.js
- src/Naturområdedetaljer/Punktinformasjon.jsx
- src/Naturområdedetaljer/VectorPointInfo.js
- src/Naturområdedetaljer/VektorPunktinformasjon.jsx
- src/__snapshots__/Storyshots.test.js.snap
> fix: Font i katalog

- public/style.yaml
- src/Grunnkart/Grunnkart.js
- src/Grunnkart/standardlag.json
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/sources.js
- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Tweaks/Polygon.js
- src/__snapshots__/Storyshots.test.js.snap
> Første test med etiketter

- src/Kodetre/Kodeliste/Tittelblokk.js
> Fix: Klikk til forelder i katalogen fungerer ikke

- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/__snapshots__/Storyshots.test.js.snap
> Kommunevåpen

- src/FetchContainer.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Tweaks/TweakContainer.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
..ved lasting av url til aktive lag som ikke lenger er aktiverte (for eksempel på grunn av en browser refresh)
eksempel:
https://naturinorge.firebaseapp.com/lag/NA
> Rut brukeren tilbake til rot

- src/Tweaks/Barneliste.js
- src/Tweaks/ColorPicker.js
- src/Tweaks/Polygon.js
- src/Tweaks/bakgrunn/Bakgrunnskart.js
- src/Tweaks/bakgrunn/Bakgrunnskartlag.js
- src/Tweaks/index.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> Justering av farger på egne kartlag og bakgrunn

- src/AktiveKartlag/PolygonlagElement.js
- src/App.css
- src/Kodetre/Kodeliste/VolumIndikator.js
- src/Kodetre/Kodeliste/VolumViz.js
- src/Tweaks/TweakContainer.js
- src/Tweaks/bakgrunn/Bakgrunnskartlag.js
- src/__snapshots__/Storyshots.test.js.snap
> Animert indikator for mengde

- src/Kart/LeafletTangram/scene/sources.js
- src/Kodetre/Kodeliste/Statistikk.js
Vis verneområder på Svalbard i kart
> Verneområder for Svalbard

- package.json
- src/Borring/BorreContainer.js
- src/Borring/Borring.js
- src/Borring/Borring.stories.js
- src/Borring/Listeelement.js
- src/Borring/a.json
- src/__mocks__/backend.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
> Kobling til levende data for punkter

- src/Borring/Borring.js
- src/Borring/Listeelement.js
- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/__snapshots__/Storyshots.test.js.snap
- src/backend.js
- src/farger.js
Sjekker respons på prefiks => farge
> Farger på bobler

- src/App.css
- src/Borring/BorreContainer.js
- src/Kart/LeafletTangram/index.js
- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Flis.js
- src/Kodetre/Kodeliste/Kodekort.js
> Logo på verneområde i kommune

- src/AktiveKartlag/index.js
- src/Borring/BorreContainer.js
- src/Borring/Listeelement.js
- src/Grunnkart/AktiveKartlagKnapp.js
- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/Flis.js
- src/SettingsContainer.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
.. så man kan se kart over hele skjermen.. litt fordel på mobil.
> Gjør det mulig å lukke katalogen (mobil)

- src/AktiveKartlag/Kartlagelement.js
- src/Grunnkart/Grunnkart.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
.. før måtte man gjøre et klikk for å få fram katalogen, nå dukker den opp med en gang.
> Vis katalog ved første lasting

- src/AktiveKartlag/Kartlagelement.js
- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/PaintSwatch.js
- src/Kodetre/Kodeliste/Tittelblokk.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
.. før kom man bare tilbake til katalogen
> Gjør det mulig å fjerne katalogen

- src/Grunnkart/standardlag.json
- src/Kart/LeafletTangram/scene/bakgrunnskart.js
> fix: Grenser var forsvunnet

- src/Kart/LeafletTangram/scene/bakgrunnskart.js
- src/Kart/LeafletTangram/scene/mal/bakgrunnskart.json
- src/Kart/LeafletTangram/scene/styles.js
> Mulighet for labels på veier

- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> +/- i kart fungerer ikke

- src/VenstreVinduContainer.js
> fix: Sletting av søkebegrep åpner katalog

- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Flis.js
- src/backend.js
> Bruk transparente PNG-filer for kommuner og organisasjoner

- src/Kodetre/Kodeliste/Kodekort.js
- src/__snapshots__/Storyshots.test.js.snap
> Utseende på kodekort

- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/Kodetre/Kodeliste/__snapshots__/ResultatListe.test.js.snap
- src/SearchBox/SearchBox.js
- src/__snapshots__/Storyshots.test.js.snap
> Tweak av søkeresultat

- src/Kodetre/Kodeliste/Statistikk.js
> fjern arter inntil tallene erpå stell

- src/SearchBox/SearchBox.js
- src/TopBar/TopBar.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> fix: Escape => Error

- src/VenstreVinduContainer.js
> Skygge på venstre vindu

- src/Tweaks/Innstilling.js
- src/__snapshots__/Storyshots.test.js.snap
>  Plassering av ikoner i kontrollpanel

- src/Kodetre/Kodeliste/Kodekort.js
- src/backend.js
> Logoer for dataleverandører

- src/Tweaks/bakgrunn/Tema.js
- src/__snapshots__/Storyshots.test.js.snap
> Layout tema

- src/Grunnkart/Grunnkart.js
- src/Grunnkart/standardlag.json
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/sources.js
- src/SearchBox/SearchBox.js
Tileset før: 
AO, MI, NA
Tileset nå:
AO
AO_03
MI_KA
> Ta i bruk nye tileset per kode istedet for per prefiks

- src/TopBar/TopBar.js
- src/VenstreVinduContainer.js
> fix: Søkebegrep blir stående etter navigering

- public/style.yaml
- src/AktiveKartlag/TerrenglagElement.js
- src/Grunnkart/Grunnkart.js
- src/Grunnkart/standardlag.json
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/terreng.js
- src/Tweaks/Polygon.js
- src/Tweaks/Terreng.js
- src/__snapshots__/Storyshots.test.js.snap
> Zoom til også for aktive lag

- src/Borring/Borring.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/VenstreVinduContainer.js
- src/backend.js
> fix: Mengdeindikator virker bare på toppnivå

- src/SearchBox/SearchBox.js
- src/SearchBox/SearchBox.stories.js
- src/__snapshots__/Storyshots.test.js.snap
> Søkeboks ux

- src/Kodetre/Kodeliste/Bildeavatar.js
> Lite hint av skygge på kommunevåpen?

- src/Kart/LeafletTangram/index.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/sources.js
> gets settings from metadata when adding sources

- src/Kodetre/Kodeliste/Kodeliste.js
> Skjul arter fra rot på katalogen

- src/Borring/BorreVindu.js
- src/Borring/Borring.js
- src/Borring/Listeelement.js
- src/Borring/Seksjon.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
Mulig å klikke på kilde og elementer under
> Vis kilder

- src/Borring/BorreVindu.js
- src/Kilde/NA/NA.js
- src/Kilde/index.js
- src/__snapshots__/Storyshots.test.js.snap
Funksjon bak knapp for å bytte mellom kilder og data
> Flikking på kilder

- package.json
- src/Borring/BorreVindu.js
- src/Kodetre/Kodetagg.js
- src/__snapshots__/Storyshots.test.js.snap
- yarn.lock
> Vis foto som sammenfaller med kartlagt natursystem

- src/Borring/BorreVindu.js
- src/Borring/Borrevalg.js
- src/Borring/Borring.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> Bilde for justering av valgmuligheter ved klikk i kart

- src/SearchBox/SearchBox.js
- src/__snapshots__/Storyshots.test.js.snap
> Search box: Ellipsis on overflowing strings

- src/Kart/LeafletTangram/index.js
- src/Kart/LeafletTangram/scene/index.js
> Load scene first time

- src/Kart/LeafletTangram/index.js
- src/Kart/LeafletTangram/scene/index.js
This reverts commit 2722bb933e7cc099447fed9944ef883f0e960002.
Denne trenger litt mer tuning
> Revert "Load scene first time (#705)"

- src/Kart/LeafletTangram/index.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/sources.js
Plukk opp bbox og zoom fra metadata, eksempel https://adb-kode.firebaseio.com//katalog/na/@.json
> Forenkling: Kartmeta i meta

- public/style.yaml
- src/Kart/LeafletTangram/scene/sources.js
Se https://nintest.artsdatabanken.no/
> Justering av urler til kartserver for å gruppere kartlag

- src/Forsidemeny/Boble.js
- src/Forsidemeny/Forsidemeny.js
- src/Kart/LeafletTangram/scene/sources.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/TopBar/TopBar.js
- src/TopBar/TopBarContainer.js
- src/__snapshots__/Storyshots.test.js.snap
- src/components/Ekspanderlinje.js
> Styling rundt søkeboks

- src/AktiveKartlag/index.js
- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/index.js
- src/Kart/LeafletTangram/scene/index.js
- src/__snapshots__/Storyshots.test.js.snap
> Make sure the map loads & updates when hovering/navigating

- src/AktiveKartlag/PolygonlagElement.js
- src/AktiveKartlag/index.js
- src/Tweaks/Barneliste.js
- src/Tweaks/Polygon.js
- src/VenstreVinduContainer.js
> Hover on active layers lights up map

- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/gradient.js
- src/Kart/LeafletTangram/scene/visualisering/point.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
> Vis også skjulte lag ved hover

- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/TopBar/TopBar.js
- src/TopBar/TopBarContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> Fix: labael over search box

- src/Kart/LeafletTangram/scene/terreng.js
Related to https://github.com/Artsdatabanken/grunnkart-dataflyt/issues/31
> Use on-premise hosted normals

- src/Kodetre/Kodeliste/Kodelisteelement.js
> Hide prefix in list

- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/styles.js
- src/Kart/LeafletTangram/scene/visualisering/gradient.js
- src/TopBar/TopBarContainer.js
- src/Tweaks/Gradient.js
- src/Tweaks/SliderSetting.js
- src/Tweaks/Tweaks.stories.js
- src/Tweaks/index.js
- src/__snapshots__/Storyshots.test.js.snap
> Gradient type source filter

- src/AktiveKartlag/TerrenglagElement.js
- src/Grunnkart/standardlag.json
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/terreng.js
- src/Tweaks/Innstilling.js
- src/Tweaks/SliderSetting.js
- src/Tweaks/Terreng.js
- src/Tweaks/Tweaks.stories.js
- src/Tweaks/Veksle.js
- src/Tweaks/bakgrunn/Bakgrunnskartlag.js
- src/Tweaks/index.js
- src/__snapshots__/Storyshots.test.js.snap
> Clean up tweak view

- docs/Dataflyt.md
> Diagram: Dataflyt

- package.json
> Auto added authors using git-authors

- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/gradient.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
- src/config.js
> fix: Refresh kart umiddelbart når lag aktiveres

- src/Borring/BorreVindu.js
- src/__snapshots__/Storyshots.test.js.snap
> Fix: 1 pixel visible in media image

- src/Kilde/NA/index.js
> Fix: Cannot read property toUppercase

- src/Tweaks/Barneliste.js
- src/Tweaks/Polygon.js
> Also allow codes to be toggled inside settings

- src/Forsidemeny/Forsidemeny.js
- src/TopBar/TopBarContainer.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
> Various layout tweaks to left menu

- src/Forsidemeny/Boble.js
- src/Forsidemeny/Forsidemeny.js
> Use sans serif fonts

- src/__snapshots__/Storyshots.test.js.snap
- src/components/Ekspanderlinje.js
> No sans serif

- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
> also show layers when they are leaf nodes

- src/Borring/Seksjon.js
- src/__snapshots__/Storyshots.test.js.snap
index.js:1452 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
in div (at Seksjon.js:92)
in p (created by Typography)
in Typography (created by WithStyles(Typography))
in WithStyles(Typography) (created by ListItemText)
in div (created by ListItemText)
in ListItemText (created by WithStyles(ListItemText))
in WithStyles(ListItemText) (at Listeelement.js:45)
>  Fix: <div> cannot appear as a descendant of <p>.

- src/Kart/LeafletTangram/scene/terreng.js
> Fix: Terrain makes water invisible

- package.json
- src/index.js
- yarn.lock
https://sentry.io/artsdatabanken/
> Test Sentry error tracking

- src/Grunnkart/Grunnkart.js
> Show page title in browser

- src/Borring/BorreVindu.js
- src/Borring/Borring.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
- src/__snapshots__/Storyshots.test.js.snap
> Knapp for å vise bare aktive lag ved klikk (mangler funksjonalitet)

- src/AktiveKartlag/AktiveKartlagKnapp.js
- src/AktiveKartlag/index.js
- src/Borring/Seksjon.js
- src/Forsidemeny/Forsidemeny.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/__snapshots__/Storyshots.test.js.snap
> Juster klikk i kart + aktive lag indikator

- src/AktiveKartlag/AktiveKartlagKnapp.js
- src/AktiveKartlag/index.js
- src/Forsidemeny/Forsidemeny.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/TopBar/TopBarContainer.js
- src/VenstreVinduContainer.js
- src/__snapshots__/Storyshots.test.js.snap
- src/components/Ekspanderlinje.js
> Animate menu elements

- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
> fix: Unable to hide child layers

- src/Forsidemeny/Forsidemeny.js
- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
- src/__snapshots__/Storyshots.test.js.snap
- src/config.js
> fix: Map disappears when zooming beyond maximum

- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
Because our code names was modified in the tile sets.
> Fix: Geometry invisible

- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
> Palette hacks

- src/Borring/Borring.js
> Fix: Klikk på element i liste etter klikk i kart fungerer ikke.

- src/Grunnkart/standardlag.json
- src/Kart/LeafletTangram/scene/bakgrunnskart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/terreng.js
- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
> Highlight properly on hover

- src/Kart/LeafletTangram/scene/visualisering/polygon.js
Mbtiles in /polygon
Mbtiles in /$code using / as seperator for levels. One mbtile pr level
> use new structure for mbtiles

- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
replace all instances of dash in mbtile-kode
special case for handling codes containing -C- and -E-
> fixes silly javascript-Replace

- src/Grunnkart/standardlag.json
> keep terrain off as default

- src/Kart/LeafletTangram/scene/visualisering/polygon.js
> use code for layer name

- src/Borring/Seksjon.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
> Klikk i kart (bare starten)

- src/Borring/BorreContainer.js
- src/TopBar/TopBarContainer.js
> Fix: Not possible to exit out of click from root

- src/Borring/BorreVindu.js
- src/Borring/FlatUt.js
- src/Borring/Listeelement.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
- src/TopBar/TopBarContainer.js
Nødvendig med reprosessering av bildearkiv
> Bilder fra NA med fallback til LA

- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
> Kompakt kodeliste

- src/backend.js
Ninmemapi @ external server
Ninmemapi @ hydra
> ninmemapi moved to hydra

- src/Borring/BorreAdapter.js
- src/Borring/BorreVindu.js
- src/Borring/Borring.js
- src/Borring/Kommunevapen.js
- src/Borring/Sted.js
- src/Kodetre/Kodeliste/BildeDialog.js
- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Flis.js
- src/Kodetre/Kodeliste/Kodekort.js
Viser resultat for klikk også utenfor Norges fylker
> Fix: Klikk i kart S3 #937

- src/MainDrawer/MainDrawer.js
- Hostes => driftes
- Pek på logo som fungerer
- Muspeker som indikerer klikkbarhet også over teksten
> hamburgermeny - endring av overskrifter #944

- src/Kart/LeafletTangram/scene/visualisering/palette/opplyst.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
Reduce saturation to none on other layers
> Highlight on hover with full saturation

- src/Forsidemeny/Boble.js
- src/Kart/LeafletTangram/scene/bakgrunnskart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/gradient.js
- src/Kart/LeafletTangram/scene/visualisering/point.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/config.js
- Skjul stedsnavn ved hoved
- Vis bare opplyste punkter
> Render point layers

- src/Forsidemeny/Boble.js
- src/Forsidemeny/Forsidemeny.js
Havner nå på riktig sted i katalogen, ikke på rot
> Knapper på forside navigasjon

- src/Borring/Sted.js
> Kommunevåpen ved klikk i kart

- src/Borring/Kommunevapen.js
- src/Forsidemeny/Boble.js
- src/Grunnkart/Grunnkart.js
- src/MainDrawer/MainDrawer.js
- src/TopBar/TopBarContainer.js
- src/Tweaks/Gradient.js
- src/Tweaks/Polygon.js
- src/VenstreVinduContainer.js
- src/components/Panel.js
https://nin.artsdatabanken.no/katalog/Natur_i_Norge/Datakilde/Artsdatabanken
https://nin.artsdatabanken.no/Natur_i_Norge/Datakilde/Artsdatabanken
> Sløyf katalog i URL

- src/Kart/LeafletTangram/scene/visualisering/polygon.js
- src/config.js
> Midlertidig justering for kartlag i 'Natur i Norge'

- src/Borring/Borring.js
- src/Grunnkart/Grunnkart.js
- src/TopBar/TopBarContainer.js
- src/VenstreVinduContainer.js
- src/backend.js
Lenker også til det dypeste nivået som representerer listeelementet.
.. blir antagelig bedre hvis vi får laget mellomsteg som viser detaljene for et listeelement
> Klikk i kart - lenke til riktig katalogelement #988

- src/Kart/LeafletTangram/scene/visualisering/gradient.js
- src/Tweaks/Polygon.js
- src/Tweaks/TweakContainer.js
- src/VenstreVinduContainer.js
> Styling knapper i visningsvindu

- src/Kodetre/Kodeliste/LinearGauge.js
> Visuell justering av gradient-indikator

- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/LinearGauge.js
>  Reduser lengden på koder i lister

- src/Kodetre/Kodeliste/LinearGauge.js
> Markering dersom gradienten ikke er kontinuerlig spekter

- src/Kodetre/Kodeliste/LinearGauge.js
> Visning av verdier i splittet gradient

- package.json
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/LinearGauge.js
- yarn.lock
> Vis koden i gradientrutene

- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Gradienter.js
- src/Kodetre/Kodeliste/Graf.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
> Vis bare del av koden som skiller seg ut

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
> Universell utforming

- src/Kodetre/Kodeliste/Kodelisteelement.js
> Måleenheter i lister

- src/Kodetre/Kodeliste/Flagg.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/Kodetre/Kodetagg.js
- src/VenstreVinduContainer.js
> Test med chip for flagg-verdier

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/ResultatListe.js
- src/Tweaks/index.js
- src/VenstreVinduContainer.js
- src/components/Panel.js
> Søkeresultater henger i friluft

- src/Kodetre/Kodeliste/LinearGauge.js
> Universell utforming: Etiketter på gradient

- src/Kodetre/Kodeliste/ResultatListe.js
- src/TopBar/TopBarContainer.js
* Forenkling
* Fjern skygge over søkeresultatet
> Søkeresultat

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/LinearGauge.js
- src/VenstreVinduContainer.js
Løsning på #1031 ispedd UI tweaks
> Katalog - umulig i klikke i katalogelement #1031

- src/Kodetre/Kodeliste/Kodelisteelement.js
> Fix: Støy i intervaller

- package.json
- src/Kart/LeafletTangram/scene/index.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/LinearGauge.js
> Kosmetisk: Skygge på trinn

- src/Kodetre/Kodeliste/Graf.js
> Lesbare overskifter for skillearter

- src/Borring/BorreVindu.js
> Knapp "Fra mine kartlag" sitter fast ved scrolling

- src/Kodetre/Kodeliste/Gradienter.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodekort.js
- src/Kodetre/Kodeliste/LinearGauge.js
> Vis hele koden

- src/Grunnkart/Grunnkart.js
istedet for å prøve å finne det ut selv
> Les nivå fra metadata

- src/Kodetre/Kodeliste/Flagg.js
... til de gode ideene kommer fram
satser på massiv støtte fra grafisk avdeling
> Vis bokstavkode på flagg

- src/Kodetre/Kodeliste/Knapperad.js
> Demp skriftfargen på knapper

- src/Kodetre/Kodeliste/Gradienter.js
- src/Kodetre/Kodeliste/Ingress.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Statistikk.js
> Vis seksjon bare hvis det finnes innhold

- src/Borring/Sted.js
> Klikk i kart - nord for fastlandsnorge

- src/Borring/BorreContainer.js
- src/Borring/Borring.js
> Vis tekst som forteller at vi ikke fant noe i punktet

- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
En del kan være kartet på mer detaljert nivå, mens en del bare finnes på typenivå, eksisterer eller ikke.  Viser begge deler.
Relatert til #1061
> Vis alle tilgjengelige kartdata på nivået

- src/Kodetre/Kodeliste/Ingress.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Statistikk/Ingress.js
> Typer mangler beskrivelse

- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Overordnet.js
> Reverser listen av overordnede

- src/Tweaks/bakgrunn/Tema.js
> Valg av tema navigerer over i tom side

- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Overordnet.js
- src/Kodetre/Kodeliste/Statistikk.js
> Statistikk virker ikke

- src/Kodetre/Kodeliste/ResultatListe.js
- src/Kodetre/Kodeliste/__snapshots__/ResultatListe.test.js.snap
Reversering av regex injection
> Ikke crash på titler med parantes

- src/AktiveKartlag/index.js
> Viser ett mindre lag enn faktisk

- src/AktiveKartlag/index.js
- src/Borring/Borring.js
- src/Kodetre/Kodeliste/Graf.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/antall.js
> Klikk i kart - gir av og til kryptiske feil i link til LA-type

- src/Kodetre/Kodeliste/Kodeliste.js
- src/Tweaks/Polygon.js
> Sorter + i LKMer etter de andre bokstavene

- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/google_raster.js
- src/Kart/LeafletTangram/scene/visualisering/gradient.js
- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
- src/Kart/LeafletTangram/scene/visualisering/openStreetMap.js
- src/Kart/LeafletTangram/scene/visualisering/point.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
- src/Kart/LeafletTangram/scene/visualisering/ruter.js
> Støtt mouseover på rasterkart

- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kurve.js
- src/Kodetre/Kodeliste/KurveContainer.js
- src/VenstreVinduContainer.js
- src/backend.js
> Starten på statistikk

- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kurve.js
- src/Kodetre/Kodeliste/KurveContainer.js
- src/Kodetre/Kodeliste/Kurver.js
- src/VenstreVinduContainer.js
Ved å legge til flere typer i "aktive"-listen og så navigere over i en en ny type er det nå mulighet for å få opp kurver for alle typene samtidig
> Støtte for mer enn 1 kurve om gangen

- src/AktiveKartlag/Kartlagelement.js
> Outline visibility knapp

- src/Kodetre/Kodeliste/Ekspander.js
- src/Kodetre/Kodeliste/Graf.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/OpenData.js
Gjør det muligens lettere å finne igjen elementer i en lang liste
> Eye "candy"

- src/Kodetre/Kodeliste/Gradienter.js
- src/Kodetre/Kodeliste/KodeVindu.js
Grupperer relasjoner til gradienter i bås under gradientrot (LKM,KLG..)
> Grupper gradienter

- src/Grunnkart/Grunnkart.js
- src/TopBar/TopBarContainer.js
> Escape fra søkeboks fjerner ikke søkeresultater

- src/Kodetre/Kodeliste/KodeVindu.js
> Husk ekspander innstilling mellom reloads

- src/Grunnkart/Grunnkart.js
- src/SearchBox/SearchBox.js
- src/TopBar/TopBar.js
- src/TopBar/TopBarContainer.js
- src/VenstreVinduContainer.js
> Lenkestruktur - bør også kunne bestå av "/-separerte" kodestreng #1134

- src/SearchBox/SearchBox.js
Sparer 1 klikk hvis man skal søke etter noe nytt
> Marker søkestreng ved første klikk

- src/TopBar/TopBarContainer.js
> Søk også når kriteriet mangler

- src/Grunnkart/Grunnkart.js
- src/SearchBox/SearchBox.js
- src/TopBar/TopBarContainer.js
- src/VenstreVinduContainer.js
#1158
F = fokus på søketekstboks, men helst ikke når du allerede står i boksen.
Mulig F var en dårlig hotkey også?
> Tasten f virker ikke

- src/Kart/LeafletTangram/scene/mal/openStreetMap.json
> Bruk internasjonale navn på kartet

- src/Kart/LeafletTangram/scene/mal/openStreetMap.json
- src/Kodetre/Kodeliste/LinearGauge.js
- src/Kodetre/Kodeliste/prettyKode.js
> Tekst over tekst i visning av gradient

- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Statistikk.js
> Statistikk: tilpasset tekst for ulike katalogelement

- src/Kodetre/Kodeliste/Statistikk.js
> søkevindu - natursystem gir 404-ish feil

- src/Borring/Borring.js
Midlertidig hack for å havne på riktig sted inntil vi får produsert ny versjon av API
> Lenker fra klikk i kart

- src/Grunnkart/Grunnkart.js
- src/Kodetre/Kodeliste/Knapperad.js
- src/Tweaks/Generelt.js
> Knapp for å fjerne aktivert sak

- src/Borring/BorreVindu.js
> Bilde mangler bed klikk i kart

- src/Kodetre/Kodeliste/ResultatListe.js
- src/LookupControl/LookupControl.js
- src/TopBar/TopBar.css
- src/TopBar/TopBar.js
> made lots of css, not correctly added

- src/Kodetre/Kodeliste/KodeVindu.js
- src/index.js
> Slå på logging av browser feilmeldinger

- src/Kodetre/Kodeliste/ResultatListe.js
- src/TopBar/TopBar.css
- fjernet to tekstlag i menyen som ikke er nødvendige, og gjorde at ting ble flytende oppå hevrandre feil
- litt mini-css som jeg trodde var på plass men tydeligvis ikke. tipper det forsvant i en merge
> removed some material design and suddenly the menu works nicely :)

- src/App.css
- src/Borring/BorreVindu.js
- src/Borring/borre.css
- src/Grunnkart/Grunnkart.js
- src/SettingsContainer.js
- src/TopBar/TopBar.css
- src/components/MobileNavigation.js
- src/components/Panel.js
> Mobile buttons :)

- src/TopBar/TopBar.css
> Tekst malpassert i forhold til knapper

- src/App.css
- src/TopBar/TopBar.css
Unnskyld at jeg har rota til... Prøvde å rette opp i et par layout issues
> Nødstiling

- src/Kart/LeafletTangram/scene/visualisering/polygon.js
Alle gode ting er tre?
https://github.com/Artsdatabanken/nin-innsyn/commit/46c0572a089871cd87d776c5141b226dd8772101#comments
> Skjul Miljødirektatets NLOD data

- src/App.css
- src/index.js
> Internet Explorer page

- src/Kodetre/Kodeliste/Knapperad.js
* Skjuler Aktiver knappen
* Skjuler Vis knappen
* Viser hele menylinjen med zoom-knapp kun hvis zoom-knapp er tilgjengelig.
> Gjemmer uønskede menyknapper fixes #1243

- src/AktiveKartlag/Kartlagelement.js
- src/Grunnkart/Grunnkart.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
- src/Kodetre/Kodeliste/Detaljeringsgrad.js
- src/Kodetre/Kodeliste/Gradienter.js
- src/Kodetre/Kodeliste/Graf.js
- src/Kodetre/Kodeliste/KodeContainer.js
- src/Kodetre/Kodeliste/KodeVindu.js
- src/Kodetre/Kodeliste/Kodeliste.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/Kodetre/Kodeliste/LinearGauge.js
- src/Kodetre/Kodeliste/Relasjon.js
- src/Tweaks/Barneliste.js
- src/Tweaks/Generelt.js
- src/VenstreVinduContainer.js
- src/index.js
- src/palette/opplyst.js
> Visualisering av landskapstyper

- src/MainDrawer/Innstillinger.js
- src/MainDrawer/MainDrawer.js
- src/MainDrawer/Menyelement.js
> Bakgrunnskart - flere valg

- .travis.yml
- deploy.sh
- slack.sh
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
Like, added some stuffs to deploy.sh and some stuffs to travis.
> Trying to implement deploy to production.

- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
> LA-KA (Kystås og kystfjell) viser helt feil polygoner i kartet.

- src/style/TopBar.css
fixes #1266 
- krympet mobil - searchboxen med en mer korrekt calc funksjon enn en litt dodgy prosent - så x'en fikk plass, voila, works.
MEGET quickfix, rask å sjekke at riktig.
> Rask fiks: x knapp virker igjen

- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
La være å prøve å rendre et kart uten source (gjelder Natursystemene vi ikke får vise)
Fix for #1302
> Navigering i natursystem gir error Unhandled promise

- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
Det som burde være enkel aritmetikk: Verdier fra 0-1 skal skaleres til verdier fra 0-255
Fixes #1312
> Marine typer vises feil.

- src/Kodetre/Kodeliste/KodeVindu.js
> fix: korrigerer for at bildet nå har endret navn

- src/MainDrawer/MainDrawer.js
> Line opp hovedmenyelement Artsdatabanken med resten

- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
Fixes #1334
Sørg for at hvert lag har sin egen style.
> Aktive lag - skjuler hverandre 

- src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js
Bjørn sliter med grunnleggende aritmetikk.  Nå ble det vel bra?  
Fixes #1333
> LA typer - viser mer enn bare en grunntype i gangen

- src/HamburgerMeny/HamburgerMeny.js
- src/Kodetre/Kodeliste/Bildeavatar.js
- src/Kodetre/Kodeliste/Kodelisteelement.js
- src/MainDrawer/MainDrawer.js
- src/TopBar/ResultatListe.js
De faktiske ikonene som brukes er out of scope for denne.  Har inntil videre bare gjenbrukt det vi har i "main drawer" (landskap/natursystem).
> Søkeresultat: Vis ikoner for alle typer

- package-lock.json
- package.json
- src/Kodetre/Kodeliste/Ekspander.js
- src/Kodetre/Kodeliste/KodeVindu.js
OnClick handler på det som tidligere var ekspanderlinja ble på et tidspunkt flyttet...  og fyrer nå av for hele boksen.
Dette førte til at den ikke lenger beholdt ekspandert tilstand ved klikk inne i boksen.
> Reparer: Husk state på ekspandere ved navigasjon

- src/Grunnkart/Grunnkart.js
- src/Grunnkart/GrunnkartFunksjoner/aktiverFraHistorikk.js
- src/Grunnkart/GrunnkartFunksjoner/aktiverValgtKartlag.js
- src/Grunnkart/GrunnkartFunksjoner/fetchMeta.js
- src/Grunnkart/GrunnkartFunksjoner/metaSjekk.js
- src/Grunnkart/GrunnkartFunksjoner/oppdaterLagProperties.js
- src/Grunnkart/GrunnkartFunksjoner/oppdaterMetaProperties.js
- src/Grunnkart/GrunnkartFunksjoner/redirectTo.js
- src/Grunnkart/GrunnkartFunksjoner/updateHistory.js
- src/Sidebar/Kartlag/Kartlag.js
- src/Sidebar/Katalog/KatalogNavigering/Navigeringsliste/NavigeringslisteFunksjoner/getKey.js
- refactor for å gjøre grunnkart mer lesbar 
- begynte på noe som må diskuteres videre, lager my branch og pr da. inntil da er ting deaktivert med har tilgjengelig det som trengs.
> Currentlayer

- src/Grunnkart/Grunnkart.js
- src/TopBar/Searchbar/Searchbar.js
- src/TopBar/TopBar.js
>  Gjør søk når brukeren peker på en "ukjent url"

- README.md
- package.json
- src/Funksjoner/backend.js
- src/Sidebar/Lokalitet/LokalitetFunksjoner/navigateToSubElement.js
- src/TopBar/TopBar.js
Var: ogapi.artsdatabanken.no
Nå: lookup.artsdatabanken.no
> Endre url til lookuptjeneste

- src/HamburgerMeny/Innstillinger.js
Etter å ha slått på visning av koder slutter hele appen å virke
> Fix: TypeError: Cannot read property 'icondisabled' of undefined

- src/Sidebar/Katalog/KatalogInformasjon/KatalogInformasjon.js
- src/style/Sidebar.css
> fixing #1376 midlertidig mens vi venter på ny versjon

- src/Kart/LeafletTangram/scene/visualisering/gradient.js
> Filter slidere fargelegger det området som er filtrert bort

- src/Sidebar/Katalog/KatalogKilder/KatalogKilder.js
Fix: Lenke til nedlastingssiden fungerer ikke.
> Fix: datakilde knapp går til undefined #1381

- src/InformasjonsVisning/Lokalitet/LokalitetElement/Landskapstype.js
- src/InformasjonsVisning/Lokalitet/LokalitetElement/Variabelboks.js
- src/style/Lokasjon.css
test lokasjon sitt utseende på ymse platformer og merge? @bjornreppen 
fixes #1431 og #1430 som er samme task X)
> mobil og paddevennlig lokasjon: part 1, grunnleggende visjon

- src/GjenbruksElement/Bildeavatar.js
- src/TopBar/ResultatListe.js
> Vis logo på alle steder

- .htaccess
TODO: ... should probably be in deployment repo since it is web server specific, irrelevant to the app
> Add .htaccess file

- src/Funksjoner/backend.js
- src/InformasjonsVisning/Lokalitet/Lokalitet.js
- src/InformasjonsVisning/Lokalitet/LokalitetElement/Stedsinfo.js
https://stedsnavn.artsdatabanken.no/10.394399832777276,63.42919692753509
> Ta i bruk nytt stedsnavn API

- src/InformasjonsVisning/Katalog/NatursystemAdvarsel.js
> Oppdatert advarsel for manglende natursystemdata

- src/AppSettings/AppFunksjoner/metaSjekk.js
- src/Funksjoner/palette/gradientrampe.js
- src/Kart/LeafletTangram/scene/index.js
- src/Kart/LeafletTangram/scene/visualisering/gradient.js
https://github.com/Artsdatabanken/nin-kart-frontend/issues/1423
Fiks for usynlig kart på KLG-trinn
> Lag paletter for løvnoder basert på det felles gradientkartet

- src/App.js
- src/HamburgerMeny/Innstillinger.js
- src/InformasjonsVisning/Katalog/Katalog.js
- src/InformasjonsVisning/Katalog/KatalogBarneliste/KatalogBarneliste.js
- src/InformasjonsVisning/Katalog/KatalogBarneliste/Navigeringsliste/KartlagBarnElement.js
- src/InformasjonsVisning/Katalog/KatalogBarneliste/Navigeringsliste/Navigeringsliste.js
- src/Kartlag/AktiveKartlag/EkspandertMeny/Filtere/GradientFilter.js
> Gradient filter slides

- package-lock.json
- package.json
-    "@artsdatabanken/typesystem": "^10.4.7",
-    "@material-ui/styles": "^4.3.3",
-    "keyboardjs": "^2.5.1",
-    "rebound": "^0.1.0",
```
npx npm-check-unused
```
> Remove unused npm dependencies

- src/Funksjoner/språk.js
- src/HamburgerMeny/HamburgerMeny.js
- src/HamburgerMeny/Innstillinger.js
> Optimalisert hamburgermeny

- src/InformasjonsVisning/Katalog/NatursystemAdvarsel.js
- src/Kartlag/AktiveKartlag/EkspanderingsTopplinje.js
- src/Kartlag/AktiveKartlag/EkspandertMeny/FellesElementer/VelgFargeBoks.js
- src/Kartlag/AktiveKartlag/EkspandertMeny/UnderElementer/LegendeComponents/LegendeElement.js
- src/Kartlag/AktiveKartlag/EkspandertMeny/Visualisering/TemaMeny/TemaMeny.js
- src/Kartlag/Historikk/HistorikkListeElement.js
- src/Kartlag/Kartlag.js
Hover for knappene for å velge farge, vise / skjule kartlag osv.
> Lagt til hover over knappene i kartet

- src/InformasjonsVisning/Katalog/KatalogHeader/KatalogHeader.js
- src/InformasjonsVisning/Katalog/NatursystemAdvarsel.js
Bare satt for de kartlaggene som forventes levert av Miljødirekatoratet
Ikke for f.eks. Erosjonsmotstand som vi får levert fra NGU
> Bruk sladd-flagg i metadata.json

- src/Kart/LeafletTangram/scene/visualisering/ruter.js
Gjør at projeksjonsproblemet ikke blir like synlig
> Overgang til solid farge fra zoom 8 til 10

- src/InformasjonsVisning/Katalog/KatalogHeader/KatalogHeaderImage.js
> fixes #1434

- src/AppSettings/AppFunksjoner/fetchMeta.js
- src/Kart/LeafletTangram/scene/index.js
Ved å sette localStorage variabel **visUpublisert** til et positivt tall er det mulig å inspisere upubliserte kart.
* 0 = i produksjon
* 1 = beta
* 2 = prototype
> Flagg upubliserte kart

- public/index.html
Fixes https://github.com/Artsdatabanken/nin-kart-frontend/issues/1505
> Tillat zoom

- src/InformasjonsVisning/Lokalitet/LokalitetElement/Variabelboks.js
- src/Kartlag/AktiveKartlag/EkspanderingsTopplinje.js
- src/Kartlag/AktiveKartlag/EkspandertMeny/FellesElementer/FargeVelger.js
- src/Kartlag/AktiveKartlag/EkspandertMeny/FellesElementer/VelgFargeBoks.js
- src/Kartlag/AktiveKartlag/EkspandertMeny/UnderElementer/LegendeComponents/LegendeElement.js
- src/Kartlag/Historikk/HistorikkListeElement.js
Lagt til mer forklarende beskrivelser av knapper og aria-label
> Lagt til mer detaljert beskrivelse i hover over knappene

- src/Kartlag/AktiveKartlag/EkspandertMeny/FellesElementer/VelgFargeBoks.js
- src/Kartlag/AktiveKartlag/EkspandertMeny/UnderElementer/LegendeComponents/LegendeElement.js
> Lagt til hover på fagreboksen

- src/Funksjoner/språk.js
- src/HamburgerMeny/Innstillinger.js
- src/InformasjonsVisning/Katalog/KatalogInformasjon/KatalogInformasjonsBoks.js
- src/InformasjonsVisning/Lokalitet/LokalitetElement/Landskapstype.js
- src/InformasjonsVisning/Lokalitet/LokalitetElement/Variabelboks.js
Tror jeg har fikset problemet med ingress
> Fikset issuen med ingress

- src/GjenbruksElement/Bildeavatar.js
- src/InformasjonsVisning/InformasjonsVisning.js
Gjør at barn f.eks. kan ha url med bare underkatalog, eks. "Fastmark"  istedet for å måtte repetere komplett url overalt.
> Tillatt både relative og "absolutte" urler

- src/InformasjonsVisning/Katalog/KatalogInformasjon/KatalogStatistikk/katalogStatistikkFunjsoner.js
Forventer katalog i overordnet
> Statistikk forårsaker kræsj

- src/Forside/ForsideInformasjon.js
Fjernet skrivefeil på forsiden
> Rettet opp skrivefeil på forsiden

- src/App.js
> Klikk i søkeresultat gir feilmelding

- src/Forside/ForsideInformasjon.js
- src/InformasjonsVisning/Katalog/KatalogGradienter/Gradienter.js
- src/InformasjonsVisning/Katalog/KatalogInformasjon/KatalogInformasjonsBoks.js
- src/InformasjonsVisning/Katalog/KatalogKilder/KatalogKilder.js
- src/MobileNavigation/MobileNavigation.js
- src/style/App.css
Byttet buttons til tabs (faner Informasjon / kart), ser ganske stygt ut
Byttet div til buttons slik at det går an å navigere på dem med tastatur
Byttet "Les mer" til url og endret lengden til 32 symboler
Lagt til "Ekstern link" og "Høyrepil" - symboler til knapper
> Gjort lenker finere

- src/App.js
- src/style/App.css
- src/style/Sidebar.css
> forhåpentligvis fikser bug som kun finnes på mobil?

- public/index.html
- src/InformasjonsVisning/Lokalitet/LokalitetElement/Variabelboks.js
> Denne gangen er jeg sikker på at den faktisk er rett.

- src/InformasjonsVisning/Lokalitet/LokalitetElement/Landskapstype.js
- src/Navigering/Meny.js
ignorer navn på branch, måtte fikse denne først :D
> fix: meny så feil ut når ekspandert og bytter mellom faner.

- src/InformasjonsVisning/Katalog/KatalogBarneliste/Navigeringsliste/KartlagBarnElement.js
- src/InformasjonsVisning/Lokalitet/LokalitetElement/Landskapstype.js
commit 1: fikser lokasjonsidelenkeknappen så den ble som før
commit 2: fikser skjoldene som var feil størrelse for boksen sin.
> fikset lokasjonssidens infoknapp øverst!

- src/Forside/ForsideInformasjon.js
- src/Forside/Kilder.js
- src/InformasjonsVisning/Lokalitet/LokalitetElement/Stedsinfo.js
- src/style/App.css
- src/style/Forside.css
Logoer til dataleverandører på forsiden har blitt til fungerende lenker.
> Gjorde logoer til dataleverandører på forsiden om til lenker

- src/Kart/LeafletTangram/Leaflet.js
http://localhost:3000/forvaltningsportalen/kart
> Fix: undefined error

- src/TopBar/TopBar.js
- src/style/GraphicProfile.scss
- src/style/TopBar.scss
tror it virks.
testa litt i chrome osv. sikkert ikke supersexy, but works
> fikset søkebar så den funker alle stedene den skal igjen tror jeg

- src/Funksjoner/backend.js
http://lookup.test.artsdatabanken.no/v1/query?q=query
> Lookup-API: Versjonert URL

- src/Funksjoner/backend.js
API docs: https://stedsnavn.test.artsdatabanken.no/
> Stedsnavn: Oppgrader til versjonert api

- src/Funksjoner/backend.js
API docs: http://punkt.artsdatabanken.no/
> Oppgrader til versjonert API

- src/InformasjonsVisning/Katalog/Klassifiseringer/Risikovurdering.js
Credits to @svetlnaumova for finding
> Arter med lenker til annet enn fab kan ikke vises

- package-lock.json
- package.json
- src/GjenbruksElement/EksternLenke.js
- src/GjenbruksElement/Lenke.js
- src/GjenbruksElement/WikiMarkdown.js
- src/InformasjonsVisning/Hjelp/Hjelp.js
- src/InformasjonsVisning/Hjelp/WikiMarkdown.js
Formål: Å gjøre det enklere for ikke-utviklere å bidra med dynamisk innhold (artikler ol.)
https://github.com/Artsdatabanken/nin-kart/wiki/Bruk
> Gjør det mulig å bruke wikisider inne i appen

- src/InformasjonsVisning/Katalog/KatalogHeader/KatalogHeaderImage.js
> TypeError: Cannot read property 'foto' of undefined

- src/GjenbruksElement/Bildeavatar.js
- src/style/App.scss
Fikser den lille feilen @bjornreppen nevnte som jeg ikke tror har noen issue?
> liten fiks for artsikon som ikke er på rekke i menyen

- src/GjenbruksElement/Bildeavatar.js
> Legg phylopic*png som logo*png for arter

- src/style/InformasjonsSider.scss
ting som ikke ble plassert riktig på underelementene på miljøvariabelsiden, blir det nå.
> liten bug, bitteliten fix

- package-lock.json
- package.json
> Bump tangram: 0.19.1

- src/index.js
> Broken link to Mozilla

- src/AppSettings/AppFunksjoner/metaSjekk.js
- src/Funksjoner/config.js
Uten prefiks i kartfila  VV-FM => FM
> Naturvern og kommuner på nytt format

- src/AppSettings/AppFunksjoner/metaSjekk.js
- src/Funksjoner/config.js
- src/Funksjoner/palette/gradientrampe.js
- src/InformasjonsVisning/Katalog/Klassifiseringer/Taksonomi.js
- src/Kart/LeafletTangram/scene/scene.js
- src/TopBar/Searchbar/Searchbar.js
- src/TopBar/TopBar.js
> Kalkkartet vises ikke

- src/Funksjoner/config.js
- src/Kart/LeafletTangram/scene/visualisering/polygon.js
Relatert til https://github.com/Artsdatabanken/nin-kart/issues/1659
> Vis punkt-data i kartet

- src/Kart/LeafletTangram/scene/visualisering/polygon.js
> Fix error when loading maps

- src/TopBar/TopBar.js
> Forkast søkeresultat for gammelt søkekriterie

- src/AppSettings/AppFunksjoner/oppdaterLagProperties.js
- src/Funksjoner/palette/gradientrampe.js
- src/InformasjonsVisning/Lokalitet/LokalitetElement/Byggeklosser.js
- src/Kart/LeafletTangram/scene/scene.js
- src/Kartlag/Kartlag.js
environment mellomnivå fjernes
> Oppgrader til å bruke nytt punkt-api

- src/AppSettings/AppFunksjoner/fetchMeta.js
- src/Funksjoner/backend.js
- src/Funksjoner/config.js
- src/GjenbruksElement/Bildeavatar.js
- src/InformasjonsVisning/Katalog/KatalogBarneliste/Navigeringsliste/KartlagBarnElement.js
- src/InformasjonsVisning/Katalog/KatalogGradienter/Gradienter.js
- src/InformasjonsVisning/Katalog/KatalogHeader/KatalogHeaderImage.js
- src/Kart/LeafletTangram/scene/visualisering/openStreetMap.js
Istedet for at alle kart og api går mot produksjon i test.
> Bruk test API i test

- .gitignore
- src/Kart/LeafletTangram/Leaflet.js
- src/Kartlegging.js
- src/style/Kart.scss
Displays only one kartlegging and all values
- Added faktaark
- Shows more than one kartlegging
- Hide row with nullvalues.
- Formatted dates dd.MM.yyyy HH:mm:ss
> Prettifying kartlegging

- src/Kartlegging.js
Display uLKM under _Natursystem_
> #1716 Display uLKM info. Added more text

- src/Kartlegging.js
> Located title

- src/App.js
- src/Funksjoner/backend.js
- src/Funksjoner/config.js
- src/Funksjoner/palette/gradientrampe.js
> #1739 Using data from mbtiles to set the bounds

- src/App.js
> #1739 check path

- src/App.js
- src/InformasjonsVisning/InformasjonsVisning.js
- src/Kart/LeafletTangram/Leaflet.js
- src/Kartlag/Kartlag.js
- src/LukkbartVindu.js
- src/Navigering/Meny.js
- src/style/App.scss
- src/style/GraphicProfile.scss
- src/style/InformasjonsSider.scss
- src/style/Kart.scss
- src/style/Kartlag.scss
- src/style/Sidebar.scss
- Cookiewarning plassert øverst, men inneholder så langt utelukkende en lenke
- Laget én funksjon for å generere markør i kartet fremfor 8 separate plasser
- Fjerna knapp for å se punktinfo, og la til åpne/lukk på kart-markørens onClick
- Er ennå en spesifikk geolocation marker som hadde eksisterende funksjon. rørte ikke den da jeg ikke vet i hvilket scenarie den dukker opp
- Fjernet kartfunksjoner for fullskjermmodus. Om vi skal ha fullskjermmodus kan det fikses med css, ikke leaflet-kart-kode.
- La til "toplayer"-variabel for lukkeboksen til informasjon, slik at den på mobil ligger forran - ikke bak - kartlagfanen, og er heldekkende.
> Punkt, Kjeks og InfoTopp

- src/App.js
- src/InformasjonsVisning/Punkt.js
- src/Kart/LeafletTangram/Leaflet.js
- src/Kart/LeafletTangram/scene/scene.js
- src/Kartlag/Kartlag.js
- src/LukkbartVindu.js
- src/style/App.scss
- src/style/InformasjonsSider.scss
- src/style/Kart.scss
- src/style/Kartlag.scss
- fullscreen big and tiny size
- tab z-index ish pls test
> Fullscreen

- src/Kartlag/Breadcrumbs.js
why on earth does everything breake on one unused import.
> remove unused var

- src/Forside/ForsideInformasjon.js
- src/style/Forside.scss
> update logo on front page
