.travis.yml

Travis would build, then delete the build, and finally deploy nothing.
skip_cleanup disables workspace delete prior to deploy

Travis skip cleanup

---

src/Kart/Mapbox/index.js
src/Kodetre/Kodeliste/KodeVindu.js
src/Kodetre/Kodeliste/KodeVindu.stories.js
src/Kodetre/Kodeliste/Kodeliste.js
src/Kodetre/Kodeliste/Kodelisteelement.js
src/Kodetre/Kodeliste/ResultatListe.stories.js
src/SearchBox/SearchBox.js
src/Storyshots.test.js
src/__snapshots__/Storyshots.test.js.snap

fjernet fargesymbol på listeelement for meta.relasjon-listene

fix #183: fjern opplyst/hover-lag også når man endrer aktivt

---

src/Kart/Mapbox/default.json

Starts at minZoom and stops trying to fetch tiles when zoom > maxZoom.

added min- and max-zoom for sqrt42

---

src/Grunnkart/Grunnkart.js

fix #342: Nullstill meta når man går ut av /katalog/ for å fjerne aktivt lag-filteret

---

src/AktiveKartlag/Kartlagelement.js
src/Grunnkart/Grunnkart.js
src/__snapshots__/Storyshots.test.js.snap

Viser fargekode selv om fargeendrings-modulen er (midlertidig?) fjernet
Kartlag som legges aktivt starter med visning på

Forbedringer etter merge av valgte lag med barn

---

src/Kart/Mapbox/index.js

fix(color): fix#185: Ta hensyn til custom transparency for valgte lag

---

src/Naturområdedetaljer/PunktinformasjonContainer.js

added localid to naturområdeinfo
show 'Ukjent' when surveyor/owner is null

Fixes #447

---

src/Kodetre/Kodeliste/KodeVindu.js
src/VenstreVinduContainer.js
src/__snapshots__/Storyshots.test.js.snap

Hard to debug as the problem only shows on mobiles and not in Chrome.
Katalog tiny
Katalog big?

Fixes #434

---

src/Grunnkart/Grunnkart.js
src/Grunnkart/standardlag.json

- But don't do it if user explicitly turned it off
Navigering i katalog til LA* slår på terreng hvis brukeren ikke har gjort et aktivt valg.

Auto enable terrain for LA

---

src/Kart/LeafletTangram/scene/visualisering/indexedRaster.js

In default settings 256x256 tiles are being overzoomed quite a lot.

Increase resolution of indexed raster tiles

---

src/Kodetre/Kodeliste/Kodelisteelement.js

Viser "<" på elementer som har tomme intervaller

---

.travis.yml

Error: Skipping a deployment with the releases provider because this repo's name does not match one specified in .[secure].yml's deploy.on.repo: [secure]en/nin-innsyn

Repair deployment from Travis

---

src/index.js

Ble skrudd av på et tidspunkt fordi vi hadde råtten kode som havnet i feilsituasjon hele tiden.

Reaktiver feillogging

---

package-lock.json
src/GjenbruksElement/Ekspander.js
src/HamburgerMeny/HamburgerMeny.js
src/HamburgerMeny/Utforsk/Utforsk.js
src/TopBar/TopBar.js

* Hamburgermenyen har fått fjernet et omliggende element som lukket ting når man tabbet i menyen
* Hamburgermenyknappen åpner nå hamburgeren ved tab, og klikkeventen er omplassert til knappen så alle events fyres på samme sted
* Hamburgermenyens interne objekter kunne alltid nås via tab-enter, men nå lukker den også dialogen etter at man har navigert seg til rett sted
* Ettersom noen av disse objektene gjenbrukes på forsiden, måtte det lages en fangst-funksjon når context ikke er tilgjengelig, for å unngå kræsj
* ekspander-tittelene ble omgjort til knapper, så de blir korrekt indexert og derav brukbare for brukere som benytter seg av tab + enter
* I kartlag, har noen objekt (fargemeny-knapp) blitt omgjort til knapper for å indexeres, og blitt angitt navnvariabler ettersom de kun …

Gjort det vesentlig lettere for brukere som benytter tab til navigering å bruke siden

---

src/InformasjonsVisning/Katalog/KatalogInformasjon/KatalogInformasjon.js
src/InformasjonsVisning/Meny/Meny/Navigeringsliste/Overordnet.js

Fjerner forutsetning om at alle typer må ha overordnet.  Det skjer ikke lenger.

Crash fordi "katalog"-nivå er borte

---

src/GjenbruksElement/Bildeavatar.js

TypeError: Cannot read property 'includes' of undefined

---

src/InformasjonsVisning/Katalog/KatalogHeader/KatalogHeaderImage.js
src/InformasjonsVisning/Lokalitet/LokalitetElement/Landskapstype.js
src/style/InformasjonsSider.scss

Når phylopic/artsfoto endret navn, feilet sjekken som stilte dem inn riktig. Nå er den endret så den bør se ok ut.
(eksempel: foto av bjørn før - sentrert og delvis utenfor boksen. nå heldekkende)

Bildene øverst på siden sto feilinstillt, er nå satt til cover.

---

src/App.js
src/HamburgerMeny/HamburgerMeny.js
src/HamburgerMeny/Utforsk/Utforsk.js
src/Kart/LeafletTangram/scene/scene.js
src/SettingsContainer.js
src/TopBar/TopBar.js

- Hovedmeny benyttet context, ikke state. Dette er uheldig adferd, da det i dette tilfellet er riktig å benytte state. Man skal ikke huske om menyen er åpen eller ikke senere. 
- Forsiden bruker ikke lenger visSplash context variabel for å tidvis vises på forsiden. Er man på url "/" får man forsiden. Er man ikke, får man kartsiden. 
fixes #1744

Hovedmeny åpnes/lukkes vha state, ikke context. Forside styres av path.

---

src/Kart/LeafletTangram/Leaflet.js
src/Kartlag/AktiveKartlag/EkspandertMeny/FellesElementer/FargeVelger.js
src/Kartlag/AktiveKartlag/EkspandertMeny/Visualisering/BgInnstillinger/BakgrunnInnstillingListeElement.js
src/Kartlag/AktiveKartlag/EkspandertMeny/Visualisering/BgInnstillinger/BakgrunnInnstillinger.js

- bakgrunnskart hadde ikke fungerende fargevelger, blant annet pga litt feilende logikk etter omplassering av elementer. Endret dem nå til å ha litt sub-bokser og inni-bokser med åpneknapp. Muligens ikke optimal løsning, men tenker good enough for nå.
- Fikset også at dobbelklikk i kart zoomet. det gir ikke mening når klikk trigger punktsetting og åpning av punkt. Da ble det rar adferd. Vil vi ha den tilbake må vi deaktivere tasteklikk for dobbelklikking.

osm_light bakgrunnsinnstilingers fargevelgere

---

src/AppSettings/AppFunksjoner/oppdaterLagProperties.js

fixes #1768
Aktive kartlag ble duplisert inn som en egen struktur.
Men endringer i interface ble bare sendt til étt lag, som ga mening slik applikasjonen var før. 
Nå derimot styres f.eks farger og opacity alltid fra current-element, så da må begge objekter targetes av oppdateringsfunksjonen, slik at de to alltid er i sync. Eneste ulempe er at har man tukla med et lag, kan man ikke få tak i orginalen uten å refreshe. Men det er kanskje greit?

favorite vs. current layer issues corrected
